import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./styles/globals.scss";
import ClientLayout from "./ClientLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Blog App",
    description: "Generated by Jeremy Duncan",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={`${inter.className} flex flex-col min-h-screen`}>
                <ClientLayout>{children}</ClientLayout>
            </body>
        </html>
    );
}
